INSERT INTO `courses` (`course_id`, `course_name`, `description`, `credits`, `category`, `semester`) VALUES
('ENGL141', 'READING AND WRITING SKILLS-I', 'Listening, Speaking, Reading, Writing, Communication Skills, Study Skills, Critical Thinking, Knowledge Application, Reading Strategies, Main Idea Identification', 3, 'core', '1st fall'),
('PHYS101', 'GENERAL PHYSICS-I', 'Engineering Problems, Physics Principles, Units and Dimensions, Kinematics, Newton''s Laws, Work and Energy, Conservation of Energy, Momentum and Collisions, Rotational Motion, Laboratory Experiments', 4, 'core', '1st fall'),
('TURK100', 'TURKISH', 'Modern Turkish Language, Alphabet Differences, Turkish Letters, Pronunciation, Basic Grammar, Sentence Structure, Present Simple Tense, Daily Communication, Demonstrative Pronouns, Family Vocabulary', 0, 'core', '1st fall'),
('MATH121', 'LINEAR ALGEBRA', 'Linear Algebra, Matrices, Matrix Operations, Systems of Linear Equations, Gaussian Elimination, Determinants, Cramer''s Rule, Vector Spaces, Dot and Cross Product, Basis and Subspaces', 2, 'core', '1st fall'),
('AIEN100', 'INTRODUCTION TO ARTIFICIAL INTELIGENCE ENGINEERING', 'Artificial Intelligence Engineering, Computer Science Fundamentals, Software Fundamentals, Data Science, Machine Learning, Robotics Applications, Information Representation, Programming Languages, Engineering Ethics, Academic Procedures', 0, 'core', '1st fall'),
('MATH101', 'CALCULUS-I', 'Differential Calculus, Integral Calculus, Functions and Graphs, Limits, L''Hospital''s Rule, Continuity, Derivatives, Applications of Derivatives, Integration Techniques, Applications of Integrals', 3, 'core', '1st fall'),
('CMPE111', 'INTRODUCTION TO PROGRAMMING', 'Computer Systems, History of Computers, Information Technology Concepts, Hardware Components, Software Components, Processor and Memory, Office Applications, Problem Solving, Flowcharting and Modular Programming, C Programming Language', 4, 'core', '1st fall'),
('ENGL142', 'READING AND WRITING SKILLS-II', 'Advanced English Skills, Listening and Speaking, Academic Writing, Compare and Contrast Essay, Venn Diagram, Conjunctions, Critical Composition, Discursive Essay, Presentation Techniques, Reading Strategies', 3, 'core', '2nd spring'),
('PHYS102', 'GENERAL PHYSICS-II', 'Electricity and Magnetism, Electric Charge, Coulomb''s Law, Electric Field, Gauss''s Law, Electric Potential, Electric Current, Ohm''s Law, Kirchhoff''s Rules, Laboratory Experiments', 4, 'core', '2nd spring'),
('HIST100', 'HISTORY OF CIVILIZATION', 'Civilization Development, Prehistoric Periods, Historic Periods, Early Civilizations, Mesopotamian Civilization, Egyptian Civilization, Classical Greek Civilization, Roman Civilization, Cultural and Social Structures, Scientific and Philosophical Aspects', 0, 'core', '2nd spring'),
('MATH122', 'DISCRETE MATHEMATICS', 'Logic and Boolean Algebra, Set Theory, Relations and Orderings, Equivalence Relations, Functions, Inductive Proofs, Recurrence Relations, Counting Techniques, Graph Theory, Graph Algorithms', 3, 'core', '2nd spring'),
('CMPE124', 'ALGORITHMS AND PROGRAMMING', 'C++ Programming, Algorithms, Flowcharts and Pseudocode, Data Types and Operators, Control Statements, Loop Structures, Functions and Recursion, Arrays, Searching and Sorting Algorithms, Pointers', 4, 'core', '2nd spring'),
('MATH102', 'CALCULUS-II', 'Sequences and Series, Convergence Tests, Power Series, Taylor and Maclaurin Series, Parametric and Polar Coordinates, Arc Length and Speed, Vector-Valued Functions, Lines and Planes, Multivariable Functions, Partial Derivatives and Multiple Integrals', 3, 'core', '2nd spring'),
('CMPE221', 'DIGITAL LOGIC DESIGN', NULL, 4, 'core', '3rd fall'),
('MATH205', 'INTRODUCTION TO PROBABILITY AND STATISTICS', NULL, 4, 'core', '3rd fall'),
('MATH203', 'DIFFERENTIAL EQUATIONS', NULL, 3, 'core', '3rd fall'),
('AIEN201', 'PRINCIPLES OF ARTIFICIAL INTELLIGENCE', NULL, 3, 'core', '3rd fall'),
('CMPE101', 'UNIVERSITY ELECTIVE (INTRODUCTION TO COMPUTING)', NULL, 3, 'elective', '3rd fall'),
('CMPE214', 'VISUAL PROGRAMMING', NULL, 3, 'core', '4th spring'),
('CMPE242', 'FREE ELECTIVE (DATA STRUCTURES AND DATA ORGANIZATION)', NULL, 4, 'elective', '4th spring'),
('INDE232', 'FREE ELECTIVE (ENGINEERING ECONOMY)', NULL, 4, 'elective', '4th spring'),
('AIEN202', 'INTRODUCTION TO DATA SCIENCE', NULL, 4, 'core', '4th spring'),
('MATH202', 'MATHEMATICAL METHODS FOR ENGINEERS', NULL, 3, 'core', '4th spring'),
('CMPE343', 'DATABASE MANAGEMENT SYSTEMS AND PROGRAMMING-I', NULL, 4, 'core', '5th fall'),
('CMPE351', 'OPERATING SYSTEMS', NULL, 4, 'core', '5th fall'),
('EELE321', 'SIGNALS & SYSTEMS', NULL, 4, 'core', '5th fall'),
('AIEN301', 'PROGRAMMING FOR ARTIFICIAL INTELLIGENCE', NULL, 3, 'core', '5th fall'),
('ENGI415', 'AREA ELECTIVE (INDUSTRIAL AUTOMATION )', NULL, 3, 'elective', '5th fall'),
('CMPE326', 'SIGNAL AND IMAGE PROCESSING', NULL, 3, 'core', '6th spring'),
('CMPE332', 'FUNDAMENTALS OF COMPUTER NETWORKS', NULL, 4, 'core', '6th spring'),
('BIME302', 'FREE ELECTIVE (PHYSIOLOGICAL SIGNALS AND INSTRUMENTATION)', NULL, 4, 'elective', '6th spring'),
('CMPE313', 'AREA ELECTIVE (OBJECT ORIENTED PROGRAMMING)', NULL, 3, 'elective', '6th spring'),
('AIEN302', 'MACHINE LEARNING', NULL, 4, 'core', '6th spring'),
('EELE411', 'ROBOTICS', NULL, 3, 'core', '7th fall'),
('ENGI401', 'PROJECT MANAGEMENT', NULL, 3, 'core', '7th fall'),
('AIEN421', 'FUNDAMENTALS OF NEURAL NETWORKS', NULL, 3, 'core', '7th fall'),
('INDE335', 'AREA ELECTIVE (ETHICS)', NULL, 3, 'elective', '7th fall'),
('AIEN300', 'SUMMER TRAINING', NULL, 0, 'core', '7th fall'),
('JOUR450', 'UNIVERSITY ELECTIVE (JOURNALISM CASE STUDIES)', NULL, 3, 'elective', '7th fall'),
('ENGI402', 'CAPSTONE PROJECT', NULL, 4, 'core', '8th spring'),
('AIEN422', 'NATURAL LANGUAGE PROCESSING', NULL, 3, 'core', '8th spring'),
('BIOE305', 'AREA ELECTIVE (BIOINFORMATICS)', NULL, 3, 'elective', '8th spring'),
('ISYE427', 'AREA ELECTIVE (INTRODUCTION TO HUMAN-COMPUTER INTERACTION)', NULL, 3, 'elective', '8th spring'),
('RTVC342', 'UNIVERSITY ELECTIVE (FILM ANALYSIS)', NULL, 4, 'elective', '8th spring');
